### ISSUE TITLE
i am getting greenscreen

### ISSUE THREAD

**Issue by sunilroyy007** [subinps/VCPlayerBot#51]
https://telegra.ph/green-colour-10-16

 i am getting green colour screen only . deployed on heroku

**Comment by sunilroyy007** [comment]
> Yes you can play index links.

weird i dont know why it takes too much ram and shows green colour screen. i will  redeploy and test again soon, will update the info

**Comment by subinps** [comment]
1. Help command is available for everyone regardless of admins or users. Since others can also read and understand the functionalities of bot.(promotion :) )
2. Yes, both bot and user needs to be in the group where it plays the music. This is because many of settings are using callback buttons which only bots can do 
3. May be heroku issues or may be issue with the file.
4. Dumb channel means channel to dumb your recordings. The CHAT var is the chat where the bot plays. I belive you have made somewhere wrong. Try changing your chat var by /env CHAT=new chat id.

**Comment by subinps** [comment]
Existing help messages will be deleted when a new use requests help again.
So it won't be a spam ig.

**Comment by sunilroyy007** [comment]
can you tell exact code to paste there if its possible or any personal message. or i need to find it lol

**Comment by sunilroyy007** [comment]
you can delete the comment on adding admin restriction. if you dont want people to know. 😁
